# Generated by Django 5.1.1 on 2024-09-07 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Profesor', 'Profesor')], max_length=10)),
                ('Autentication', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora_Inicio', models.TimeField()),
                ('Hora_Fin', models.TimeField()),
                ('Aula', models.CharField(blank=True, max_length=50, null=True)),
                ('Notas', models.TextField(blank=True, null=True)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Fecha', models.DateField()),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Fecha_limite', models.DateField()),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Mensaje', models.TextField()),
                ('Fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('Clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.clase')),
                ('Curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.curso')),
                ('Evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.evaluacion')),
                ('Tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.tarea')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='Profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.curso')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.usuario')),
            ],
            options={
                'unique_together': {('Usuario', 'Curso')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='Estudiantes',
            field=models.ManyToManyField(related_name='cursos', through='clases.UsuarioCurso', to='clases.usuario'),
        ),
    ]
