# Generated by Django 5.1.2 on 2024-11-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarV2app', '0002_alter_horario_asignatura_alter_horario_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='calendarV2app.asignatura'),
        ),
    ]
