# Generated by Django 5.1.2 on 2024-11-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarV2app', '0004_remove_usuario_contraseña_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_admin',
            new_name='is_staff',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
