# Generated by Django 5.1.1 on 2024-09-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_rename_autentication_usuario_autenticacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Autenticacion',
            field=models.TextField(),
        ),
    ]
